//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikl()
        {
            this.Stavke_narudzbe = new HashSet<Stavke_narudzbe>();
        }
    
        public int ID_artikla { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public string Proizvodac { get; set; }
        public Nullable<decimal> Cijena { get; set; }
        public string Serijski_broj { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavke_narudzbe> Stavke_narudzbe { get; set; }
    }
}
