//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ovlasti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ovlasti()
        {
            this.Korisnik = new HashSet<Korisnik>();
        }
    
        public int ID_ovlasti { get; set; }
        public Nullable<bool> Unos_artikla { get; set; }
        public Nullable<bool> Azuriranje_artikla { get; set; }
        public Nullable<bool> Brisanje_artikla { get; set; }
        public Nullable<bool> Odobravanje_narudzbe { get; set; }
        public Nullable<bool> Uredivanje_ovlasti { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Korisnik> Korisnik { get; set; }
    }
}
