//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavke_narudzbe
    {
        public int ID_stavke { get; set; }
        public Nullable<int> NarudzbaID_narudzbe { get; set; }
        public Nullable<int> ArtiklID_artikla { get; set; }
        public Nullable<int> Kolicina { get; set; }
    
        public virtual Artikl Artikl { get; set; }
        public virtual Narudzba Narudzba { get; set; }
    }
}
