//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uredaj_Servis
    {
        public int ID_uredaj_servis { get; set; }
        public Nullable<int> KorisnikID_korisnika { get; set; }
        public string Naziv { get; set; }
        public string Model { get; set; }
        public string Proizvodac { get; set; }
        public string Serijski_broj { get; set; }
        public string Opis_kvara { get; set; }
        public byte[] QR_kod { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
